resume:
pretrain:
    split: False
    pretrain: ./exp/DFDC/last_model.pt
seed: 1024
data:
    dataset: DFDC
    modality: RGB
    batch_size: 8
    workers: 16
    image_tmpl: 'img_{:05d}.jpg'
    train_face_list: 'lists/DFDC/train_frame_new.txt'
    val_face_list: 'lists/DFDC/test_frame_new.txt' #
    label_list: 'lists/DFDC.csv'
    index_bias: 1
    input_size: 224
    neg_sample: 10
    randaug:
        N: 2 #2
        M: 9  #9
    random_shift: True
    exp_name: test_DFDC

network:
    arch: Transf
    init: True
    tsm: False
    drop_out: 0.0
    MM: True
    layers: 12
    emb_dropout: 0.0
    type: Tranf_face
    sim_header: "Transf"
    joint: False
    describe:
    id_num: 2
    voice:
      input_resolution: [128, 256]
      patch_size: 32
      width: 768
      layers: 12
      heads: 12
      output_dim: 512
    face:
      input_resolution: 224
      patch_size: 32
      width: 768
      layers: 12
      heads: 12
      output_dim: 512

solver:
    type: cosine
    epochs: 20
    start_epoch: 0
    epoch_offset: 0
    optim: adamw
    lr: 5.e-6 #5.e-6
    lr_warmup_step: 2
    momentum: 0.9
    weight_decay: 0.2
    lr_decay_step: 15
    lr_decay_factor: 0.1
    clip_gradient: 20
    loss_type: nll
    evaluate: True
    ratio: 1
    f_ratio: 1
logging:
    print_freq: 10
    eval_freq: 1